export const MATCH_COMMENTARY = {
  early: [
    "Maçın temposu oldukça düşük başladı. İki takım da birbirini tartıyor.",
    "Tribünler bugün tıklım tıklım, muazzam bir atmosfer var.",
    "Takımlar henüz risk almıyor, oyun daha çok orta sahada geçiyor.",
    "Hava oldukça güzel, zemin futbol oynamaya elverişli.",
    "İki teknik direktör de maça temkinli başladı.",
    "Maçın ilk dakikalarında karşılıklı pas hataları görüyoruz.",
    "Oyun henüz ısınmadı, {HOME:name} ve arkadaşları yerlerini almaya çalışıyor.",
    "{AWAY:name} maça oldukça konsantre başlamış görünüyor."
  ],
  mid: [
    "Müthiş bir pres var sahada! Oyuncular nefes almıyor.",
    "Top bir o kalede bir bu kalede, tempo iyice yükseldi.",
    "Hakem avantaja bıraktı, {HOME:name} oyunu sürdürüyor.",
    "Orta sahada kıran kırana bir mücadele izliyoruz.",
    "Pas trafiği çok akıcı bugün, {AWAY:name} top paylaşımında etkili.",
    "Kritik bir müdahale! {HOME:name} tehlikeyi uzaklaştırdı.",
    "Orta sahadaki pas hataları oyunun ritmini bozuyor.",
    "Hızlı bir hücum denemesi ama {AWAY:name} top kaybıyla sonuçlandı.",
    "Defansın derinliği düşündürücü, {HOME:name} arkada boşluklar veriyor.",
    "Oyunun kontrolü tamamen orta sahadaki mücadeleye bağlı.",
    "Müthiş bir organizasyon! {HOME:name} pasını verdi ama adrese ulaşmadı.",
    "Top kaybı tehlikeli noktada! {AWAY:name} kademeye girmekte gecikti.",
    "Kanatlardan gelen bindirmeler etkili olmaya başladı.",
    "Fiziksel güç bugün maçın belirleyici faktörü olacak.",
    "{HOME:name} ceza sahası önünde büyük bir baskı kurdu.",
    "Savunma oyuncuları birbirlerine çok yakın oynuyor.",
    "Orta sahayı kalabalık tutan ekip oyunun hakimi.",
    "Topu ayağında tutan taraf tempoyu ayarlıyor.",
    "{AWAY:name} kanatlarda boşluk arıyor.",
    "Kısa paslarla oyun kurmaya çalışıyorlar.",
    "Mücadele dozu çok yüksek, {HOME:name} pes etmiyor.",
    "Oyun geniş alana yayıldı, fiziksel dayanıklılık ön planda.",
    "Sahada yardımlaşma üst seviyede.",
    "Müthiş bir pas organizasyonu, {AWAY:name} seyir zevkini artırıyor."
  ],
  late: [
    "Oyuncuların yorgunluk belirtileri göstermeye başladığını görüyoruz, özellikle {HOME:name} çok yoruldu.",
    "Yedek kulübesi hareketlendi, {AWAY:name} için bir değişiklik gelebilir.",
    "Zaman geçirme çabaları tribünlerin tepkisini çekiyor.",
    "Maçın bitimine yaklaştıkça heyecan daha da artıyor.",
    "Maçın en kritik dakikalarına giriyoruz.",
    "Oyuncularda konsantrasyon kaybı gözlemleniyor.",
    "Oyunun ritmi düştü, {HOME:name} tempoyu artırmak zorunda.",
    "Yorgunluktan dolayı pas hataları artmaya başladı.",
    "{AWAY:name} sorumluluk alıyor, takımı ileri taşıyor.",
    "Maçın kaderini belirleyecek dakikalar yaklaşıyor.",
    "Sonsuz bir enerjiyle koşmaya devam ediyorlar.",
    "Teknik direktörler her topun can alıcı olduğunun farkında."
  ],
  anytime: [
    "{HOME:name} bugün kalesinde adeta devleşiyor.",
    "Sert bir müdahale geldi, hakem {AWAY:name}'i uyarıyor.",
    "Korner atışı kullanılacak, {HOME:name} ceza sahasında pozisyon alıyor.",
    "Uzaklardan bir şut! {AWAY:name} vurdu, top az farkla auta gidiyor.",
    "Müthiş bir çalım! {HOME:name} tribünleri ayağa kaldtı.",
    "Savunma hatasız oynuyor, {AWAY:name} geçit vermiyor.",
    "Dirençli bir oyun var sahada, iki takım da geri adım atmıyor.",
    "Hava toplarında bugün ev sahibi ekibin üstünlüğü var.",
    "Direkten dönen top! {HOME:name} için inanılmaz bir an!",
    "Kaleciyle karşı karşıya! {AWAY:name} vuruşunu yaptı ama çok zayıf.",
    "Faul beklentisi var ama hakem {HOME:name}'e 'devam' dedi.",
    "{AWAY:name} arkadaşlarına sakin olmalarını söylüyor.",
    "Harika bir ayak içi plase ama {HOME:name} kalesinde başarılı.",
    "Aşırtma vuruş denemesi! {AWAY:name} vurdu ama top üst ağlarda kaldı.",
    "Müthiş bir rövaşata denemesi! {HOME:name} az daha yılın golünü atıyordu.",
    "Savunma hattı bugün çok disiplinli görünüyor.",
    "{AWAY:name} klas bir hareketle rakiplerini tek tek geçti.",
    "Hatalı bir pas, {HOME:name} için tehlike kapıda!",
    "Şık bir verkaç pozisyonu, {AWAY:name} ceza sahasına girdi.",
    "Uzak direğe bir kafa vuruşu! {HOME:name} kritik bir müdahale yaptı.",
    "Hatalı bir çıkış, {AWAY:name} kalesinde tehlikeli anlar.",
    "Defans çizgi halinde bekliyor, ofsayt taktiği.",
    "Kritik bir pas arası, {HOME:name} kontra atağı başlattı.",
    "Frikikte topun başında {AWAY:name} var.",
    "Şut açısı arıyor, ama {HOME:name} savunması kapattı.",
    "{AWAY:name} topu auta gönderdi, büyük bir fırsat kaçtı.",
    "{HOME:name} taktiksel bir faul ile tehlikeyi büyümeden önledi.",
    "Tribünler gol diye ayağa kalktı ama {AWAY:name}'in şutu dışarıda.",
    "Kaleci topu tokatlayarak kornere gönderdi."
  ],
  offside_trap: [
    "Savunma hattı birlikte ileri atıldı! Ofsayt tuzağı kusursuz çalışıyor.",
    "Stoperlerin senkronizasyonu mükemmel! Rakip forvet ofsayt çizgisinde sıkıştı.",
    "Yüksek savunma hattıyla ofsayt tuzağı kuruluyor ve başarıyla uygulanıyor.",
    "Ofsayt tuzağı devrede! Savunma hattının disiplini rakip forvetleri çaresiz bıraktı.",
    "Birlikte hareket eden savunma hattı, rakip hücumunu ofsayt tuzağıyla böğdü.",
    "Ofsayt tuzağı zamanlaması hatasız çalışıyor, rakip forvetler açılış pozisyonu bulamıyor.",
    "Hakem sürekli bayrağı kaldırıyor! Savunma hattının ofsayt tuzağı çok etkili.",
    "Savunma hattı adeta tek bir vücut gibi hareket ediyor, ofsayt tuzağı mükemmel.",
    "Rakip teknik direktör ofsayt tuzağına karşı çare arıyor ama bulamıyor.",
    "Ofsayt tuzağı sayesinde rakip hızlı forvetler etkisiz hale getirildi.",
    "Konsantrasyon ve iletişim mükemmel! Ofsayt tuzağı her seferinde tutuyor.",
    "Savunma hattının yukarıda kalması ofsayt tuzağını daha da etkili kılıyor."
  ],
  offside_trap_failed: [
    "Ofsayt tuzağı bozuldu! Stoperler arasındaki uyum kayboldu, ciddi tehlike!",
    "Zamanlama hatası! Ofsayt tuzağı tutmadı ve rakip forvet tek başına kaleciyle karşı karşıya!",
    "Savunma hattı yarıldı! Ofsayt tuzağı çalışmadı, büyük bir kaos yaşanıyor.",
    "Ofsayt tuzağı riski! Stoperler arası mesafe açıldı ve rakip buna ceza verdi.",
    "Ofsayt tuzağında iletişim kopukluğu! Savunma arkası tamamen açıldı.",
    "Yüksek savunma hattının bedeli ağır oldu! Ofsayt tuzağı tutmadı.",
    "Stoperlerden birinin geç kalması ofsayt tuzağını bozdu, tehlikeli bir an!",
    "Ofsayt tuzağı kurmaya çalıştılar ama rakip forvet hızlı sızdı, büyük fırsat!"
  ]
};
